### ISSUE TITLE
Add more product Id's

### ISSUE THREAD

**Issue by 1234Eliaquim1234** [onlimono/mv-android-client-IAP#7]
hi onlimono !
I'm studying ways to add a donation button in the game, like $1, $3, $5, etc...
So, I want to know if with your implementation of IAP services, I already can do that.
Or I will only be able to use this kind of app purchase demo/full version of the game?

And, about the script call:
"window.IAP.purchased()"
I have to put the ID of my product inside the () like a string?
window.IAP.purchased("myProductId")

Can I put more than one product for people to buy?

For example, let's say I have two products:
**myProductId1
myProductId2**

How can I specify in a conditional branch if the player has purchased a specific product(Assuming I can sell more than one product)?

Code:
_if(window.IAP.purchased("myProductId1") == true) {
// do stuff};
 
if(window.IAP.purchased("myProductId2") == true) {
// do stuff};_

I send this message in the forum too, but I don't know if you are active there... so I put this doubt here.

**Comment by onlimono** [comment]
Sorry for late response. I think you can do that.
Refer here: https://github.com/anjlab/android-inapp-billing-v3.
