### ISSUE TITLE
Game resets if the user open "window.IAP.purchaseGame()" and don't buy.

### ISSUE THREAD

**Issue by EliaquimNascimento** [onlimono/mv-android-client-IAP#8]
I made an event with the script call "window.IAP.purchaseGame()", just for test if everything is ok.
So the window for purchase is open. 
But when I decide to not buy, if I press on the back button of android OR touch at any point on the screen, outside the purchase's window, the game resets automatically.
How can I handle this?

**Comment by onlimono** [comment]
Sorry for late response.
Just delete

finish();
startActivity(getIntent());

at onProductPurchased and onBillingError in /app/src/main/java/systems/altimit/rpgmakermv/WebPlayerActivity.java.

But, there may be some memory problems, and I recommend you to modify the billing system.
